In [2]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [3]:
print(f"Numpy version: {np.__version__}")
np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.2


In [4]:
# creating arrays from python lists
#1D: a simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])
#2D: array: a matrix or table with rows and columns
arrd2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
#3D array: like a stack of 2D arrays - useful for images, time series e.tc 
arrd3 = np.array([[[1,3],[2,4]],
                  [[5,7],[9,6]]])

print("1D Array:",arr1d)
print("2D Array:\n",arrd2)
print("3D Array:\n",arrd3)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 3]
  [2 4]]

 [[5 7]
  [9 6]]]


In [5]:
# creating arrays filled with zeros - useful for initializing arrays
# shape(3,4) rows first coulmsns second
zeros = np.zeros((3,4))

# creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))

# empty array - faster than 0s and 1s but contains random values
empty = np.empty((2, 2))

print("Zero Array(3x4):",zeros)
print("Ones array  Array:\n",ones)
print("Ones array  Array:\n",ones.shape)
print("Empty Array(contains random numbers):\n",empty)

Zero Array(3x4): [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array  Array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Ones array  Array:
 (2, 3, 4)
Empty Array(contains random numbers):
 [[0. 0.]
 [0. 0.]]


In [6]:
# range arrays - like python's range() but more powerful
range_arr = np.arange(0, 10, 2)
print("Range array:",range_arr)

#linearly spaced arrays - divide a range into equal parts
# From 0 to 1 with exactly 5 points (including endpoints)
linespace_arr = np.linspace(0, 1, 5)
print("Linspace array:",linespace_arr)


# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 1, 5)  
print("Logspace array:", logspace_arr)


Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [ 1.     1.778  3.162  5.623 10.   ]


In [7]:
# identy matrix
identity = np.eye(6)
print("Identity matrix:\n", identity)

diagonal = np.diag([1, 2, 3, 4])
print("Diagonal matrix:\n", diagonal)


full_arr = np.full((3,3),7)
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
int_arr = np.array([1, 2, 3], dtype= np.int32)
float_arr = np.array([1, 2, 3], dtype= np.float64)
bool_arr = np.array([True, False, True], dtype= np.int32)
converted = int_arr.astype(np.float32) 


print("Integer array dtype:", int_arr.dtype)
print("Integer array :", int_arr)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)


print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Integer array : [1 2 3]
Float array dtype: float64
Boolean array dtype: int32
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element


In [9]:
arr = np.random.randn(3, 4, 5)
print("Array", arr)  
# Shape: The dimensions of the array (layers, rows, columns)
print("Shape:", arr.shape)   
# Size: Total number of elements (3 × 4 × 5 = 60)
print("Size:", arr.size)  
# Dtype: Data type of elements
print("Dtype:", arr.dtype)           # Usually float64 for random numbers
# Itemsize: Memory size of each element in bytes
print("Itemsize:", arr.itemsize) 
# Total memory usage in bytes
print("Memory usage:", arr.nbytes, "bytes")  # size × itemsize
print("Memory usage:", arr.nbytes / 1024, "KB") 


Array [[[ 0.154  1.078  0.804  0.089 -1.126]
  [ 0.702 -1.861  1.059  0.324  1.794]
  [ 0.415 -1.534  0.629 -0.377 -2.053]
  [ 0.42   1.842 -0.076 -0.517  0.979]]

 [[-0.411  0.509  0.945 -0.055 -0.215]
  [ 0.771 -0.066 -0.277  1.026  0.757]
  [-0.209 -1.755 -0.535 -1.381 -0.045]
  [-0.752 -0.939  0.2   -1.114 -0.256]]

 [[ 1.758  0.041  0.235  0.135  1.465]
  [ 0.55  -1.268 -0.204  0.403  0.272]
  [-0.65   1.063  1.632 -1.088 -0.521]
  [ 0.979 -1.077 -1.261 -0.681 -0.315]]]
Shape: (3, 4, 5)
Size: 60
Dtype: float64
Itemsize: 8
Memory usage: 480 bytes
Memory usage: 0.46875 KB


In [10]:
arr1d1 = np.array([10, 20, 30, 40 ,50])
print("First element:", arr1d1[0])
print("First element:", arr1d1[1]) 
print("First element:", arr1d1[-1]) 
print("First element:", arr1d1[1:4]) 
print("First element:", arr1d1[::2]) 

First element: 10
First element: 20
First element: 50
First element: [20 30 40]
First element: [10 30 50]


In [11]:
arr1d2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [3, 4, 5, 6]])

# Access specific element: [row, column]
print("Element at row 1, column 2:", arr1d2[1, 2])  
# Access entire rows or columns
print("First row:",  arr1d2[0, :])
print("Second column:",   arr1d2[:, 1])    
# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2):\n",  arr1d2[1:3, 1:3])

Element at row 1, column 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10  4]
Subarray (rows 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])  # Select elements at positions 0, 2, 4
print("Fancy indexing:", arr[indices]) 

random_indices = np.array([4, 1, 3, 1])
print("Random Order:", arr[random_indices])

Fancy indexing: [10 30 50]
Random Order: [50 20 40 20]


In [32]:
arrdd2 = np.arange(12).reshape(3,4)
print("Original 2D array:\n", arrdd2)


rows = np.array([0,2])
cols = np.array([1, 3])

print("Elements at (0,1) and (2,3):",arrdd2[rows, cols]) 

Original 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elements at (0,1) and (2,3): [ 1 11]
