### Linear Algebra Case Study

2. Problem Setup

We have the scores of 4 students in 3 subjects (Mathematics, English, Science):

Student Math English Science

Student 1 80 70 90

Student 2 60 85 75

Student 3 95 88 92

Student 4 70 60 65


## 3.1 Representing Data as a Matrix
let A =
\begin{bmatrix}
80 & 70 & 90 \\ 60 & 85 & 75 \\ 95 & 88 & 92 \\ 70 & 60 & 65
\end{bmatrix}

## 3.2 Total Scores per Student (Vector Addition)

summing across the row vector.

 Total student 1 scores [80, 70, 90] = 240

 Total student 2 scores [60, 85, 75] = 220

 Total student 3 scores [95, 88, 92] = 275

 Total student 4 scores [70, 60, 65] = 195
 
let Total score =
\begin{bmatrix}
240 \\ 220 \\ 275 \\ 195
\end{bmatrix}

## 3.3 Applying Weights (Scalar Multiplication)

let A =
\begin{bmatrix}
80 & 70 & 90 \\ 60 & 85 & 75 \\ 95 & 88 & 92 \\ 70 & 60 & 65
\end{bmatrix}

let Scalar = 2

scale the vector across the first colunm:
R_s =
\begin{bmatrix}
80 \\ 60 \\ 95 \\ 70 
\end{bmatrix}     × 2  = 

\begin{bmatrix}
160 \\ 120 \\ 190 \\ 140
\end{bmatrix} 

Scaled A (along the first colunm) =

\begin{bmatrix}
160 & 70 & 90 \\ 120 & 85 & 75 \\ 190 & 88 & 92 \\ 140 & 60 & 65
\end{bmatrix}



## 3.4 Average Score per Subject (Matrix Operations)
Average score for each subject(Math):
\begin{bmatrix}
80 \\ 60 \\ 95 \\ 70 
\end{bmatrix}     / 4 =  76.25

Average score for each subject(English):
\begin{bmatrix}
70 \\ 85 \\ 88 \\ 60
\end{bmatrix}     / 4 =  75.75

Average score for each subject(Science):
\begin{bmatrix}
90 \\ 75 \\ 92 \\ 65
\end{bmatrix}     / 4 =  80.5

## 3.5 Final Grades using Matrix Multiplication
weight vector = ([0.5, 0.3, 0.2])

Student Score = 
\begin{bmatrix}
80 & 70 & 90 \\ 60 & 85 & 75 \\ 95 & 88 & 92 \\ 70 & 60 & 65
\end{bmatrix}

Final grade = 
\begin{bmatrix}
0.5 \\ 0.3 \\ 0.2
\end{bmatrix}  × 

\begin{bmatrix}
80 & 70 & 90 \\ 60 & 85 & 75 \\ 95 & 88 & 92 \\ 70 & 60 & 65
\end{bmatrix}  =

\begin{bmatrix}
79 \\ 70.5 \\ 92.3 \\ 66
\end{bmatrix}  

## 3.6 Comparing Students (Vector Subtraction)

\begin{bmatrix}
Student 3 & 95 & 88 & 92 
\end{bmatrix}  -

\begin{bmatrix}
Student 2 & 60 & 85 & 75 
\end{bmatrix}

=

\begin{bmatrix}
35 & 3 & 17
\end{bmatrix}




 



In [2]:
import numpy as np

In [3]:
# 3.1 Representing Data as a Matrix
data = np.array([[80, 70, 90],
[60, 85, 75],
[95, 88, 92],
[70, 60, 65]])
print(f"Here is the data represented as a (4×3)\n {data}")



Here is the data represented as a (4×3)
 [[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


In [4]:
# 3.2 Total Scores per Student (Vector Addition) 
print("Total Score per Student:", np.sum(data, axis=1))  

Total Score per Student: [240 220 275 195]


In [5]:
# 3.3 Applying Weights (Scalar Multiplication)
data = np.array([[80, 70, 90],
[60, 85, 75],
[95, 88, 92],
[70, 60, 65]])
print("\nMatrix before scalar multiplication on column")
print(data)
colunm_to_scale = data[:, 0]
print(f"\nMaths colunm to be scaled: {colunm_to_scale}")
column_index = 0
scalar_value = 2

data[:, column_index ] *= scalar_value 
print("\nMatrix after scalar multiplication on column", column_index, ":")
print(data)



Matrix before scalar multiplication on column
[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]

Maths colunm to be scaled: [80 60 95 70]

Matrix after scalar multiplication on column 0 :
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [6]:
#3.4 Average Score per Subject (Matrix Operations)
data1 = np.array([[80, 70, 90],
[60, 85, 75],
[95, 88, 92],
[70, 60, 65]])
column_means = np.mean(data1, axis=0)              
print("Column means:", column_means)

Column means: [76.25 75.75 80.5 ]


In [7]:
# 3.5 Final Grades using Matrix Multiplication
data1 = np.array([[80, 70, 90],
[60, 85, 75],
[95, 88, 92],
[70, 60, 65]])
weight_vector = np.array([[0.5], [0.3], [0.2]])  
final_grade = np.dot(data1, weight_vector)
print(f"Final Grade:\n {final_grade}")

Final Grade:
 [[79. ]
 [70.5]
 [92.3]
 [66. ]]


In [8]:
# 3.6 Comparing Students (Vector Subtraction)
student_3 = np.array([95, 88, 92])
student_2 = np.array([60, 85, 75])

vector_subtraction = student_3 - student_2

vector_subtraction



array([35,  3, 17])

## 5. Add-on Exercises

1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total
score and the average per subject.

2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar
multiplication and recompute totals.

3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using
matrix multiplication.

4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each
subject?

In [12]:
# Create a new 5×4 matrix of scores (5 students, 4 subjects)
new_data = np.random.randint(65, 101,(5,4))
print(f"Here is the new data represented as a (5×4)\n[Maths, English, Science, Civic]\n {new_data}")

Here is the new data represented as a (5×4)
[Maths, English, Science, Civic]
 [[ 97  96  73  78]
 [ 98 100  92  95]
 [ 72  81  75  86]
 [ 75  80  86  78]
 [ 88  65  75  84]]


In [10]:
# 1.1 Total Scores per Student (Vector Addition) 
total_score_per_student = np.sum(new_data, axis=1)
print("Total Score per Student:", total_score_per_student) 
#1.2 Average Score per Subject (Matrix Operations)
colu = np.mean(data1, axis=0)              
print("Column means:", column_means) 

Total Score per Student: [347 320 325 350 337]
Column means: [76.25 75.75 80.5 ]


In [ ]:
# 2 Applying Weights (Scalar Multiplication)

print("\nMatrix before scalar multiplication on column")
print(new_data)
colunm_to_scale = new_data[:, 2]
print(f"\nScience colunm to be scaled: {colunm_to_scale}")
column_index = 2
scalar_value = 3

new_data[:, column_index ] *= scalar_value 
print("\nMatrix after scalar multiplication on column", column_index, ":")
print(new_data)


Matrix before scalar multiplication on column
[[ 97  96  73  78]
 [ 98 100  92  95]
 [ 72  81  75  86]
 [ 75  80  86  78]
 [ 88  65  75  84]]

Maths colunm to be scaled: [73 92 75 86 75]

Matrix after scalar multiplication on column 2 :
[[ 97  96 219  78]
 [ 98 100 276  95]
 [ 72  81 225  86]
 [ 75  80 258  78]
 [ 88  65 225  84]]
