In [37]:
import numpy as np

Question 1:  Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

In [38]:
#Question 1
arr = np.random.randint(1, 50,(6,6))

print("The Original Array:",arr)

The Original Array: [[26  9  1  3 46 17]
 [32 23 19  7  9 26]
 [36  2  4 26 19 17]
 [12 40  9 21  1  3]
 [25 31 25 41 40  8]
 [39 34  7 37 16  1]]


Question 2: Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

In [59]:
print("The first two rows:", arr[:2, :])  
print("The last 3 columns:\n", arr[:, 3:])  
even_num = np.array(arr % 2 == 0)
print("Even Array:", arr[even_num])

The first two rows: [[26  9  1  3 46 17]
 [32 23 19  7  9 26]]
The last 3 columns:
 [[ 3 46 17]
 [ 7  9 26]
 [26 19 17]
 [21  1  3]
 [41 40  8]
 [37 16  1]]
Even Array: [26 46 32 26 36  2  4 26 12 40 40  8 34 16]


Question 3: Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [41]:
arr2 = arr.reshape(3,2,6)
print("The Reshaped Array:",arr2)
flattened = arr2.flatten()                 
print("Flattened (copy):\n", flattened)


The Reshaped Array: [[[26  9  1  3 46 17]
  [32 23 19  7  9 26]]

 [[36  2  4 26 19 17]
  [12 40  9 21  1  3]]

 [[25 31 25 41 40  8]
  [39 34  7 37 16  1]]]
Flattened (copy):
 [26  9  1  3 46 17 32 23 19  7  9 26 36  2  4 26 19 17 12 40  9 21  1  3
 25 31 25 41 40  8 39 34  7 37 16  1]



Question 4: Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [45]:
arr_id = np.eye(4)
print("Identity matrix:\n",arr_id)
arr_diag = np.arange(10, 50, 10)
arr2_diag = np.diag(arr_diag)
print("Diagonal matrix:\n", arr2_diag)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


Question 5: Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [61]:
arr_3_4 = np.random.randint(1, 10,(3,4))
print("The 3 by 4 array:",arr_3_4)
arr_4_3= np.random.randint(1, 10,(4,3))
print("The 4 by 3 array:",arr_4_3)
print("Multiplication by mat mull:", np.matmul(arr_3_4, arr_4_3))


The 3 by 4 array: [[8 1 9 8]
 [2 8 8 1]
 [5 7 9 8]]
The 4 by 3 array: [[7 6 9]
 [7 2 4]
 [5 9 1]
 [2 1 5]]
Multiplication by mat mull: [[124 139 125]
 [112 101  63]
 [145 133 122]]


Question 6: Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [75]:
def arr():
     z = int(input("Enter the lower limit: "))
     u = int(input("Enter the upper limit: "))
     x = int(input("Enter the number of rows: "))
     y = int(input("Enter the number of coulmns: "))
     arrd_2D = np.random.randint(z, u,(x,y))
     print("Original Array:", arrd_2D)
     if arrd_2D.ndim == 2:
        arrd_2D_copy = arrd_2D.copy()
        square_mask = np.where(arrd_2D_copy %  2 == 0, np.square(arrd_2D_copy), arrd_2D_copy)
        odd_mask = np.where(square_mask % 2 != 0, -1, square_mask)
        return odd_mask
     else:
         print("Array not the right dimension")


arr()

Original Array: [[23 36 20 31]
 [12 29  8 23]
 [11 38 14 29]]


array([[  -1, 1296,  400,   -1],
       [ 144,   -1,   64,   -1],
       [  -1, 1444,  196,   -1]], dtype=int32)

In [ ]:
def arr():
   
     arrd_2D = np.random.randint(z, u,(x,y))
     print("Original Array:", arrd_2D)
     if arrd_2D.ndim == 2:
        arrd_2D_copy = arrd_2D.copy()
        square_mask = np.where(arrd_2D_copy %  2 == 0, np.square(arrd_2D_copy), arrd_2D_copy)
        odd_mask = np.where(square_mask % 2 != 0, -1, square_mask)
        return odd_mask
     else:
         print("Array not the right dimension")